# Generated by Django 5.1.6 on 2025-02-28 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0002_event_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='created_by',
        ),
    ]
