# Generated by Django 5.1.6 on 2025-02-28 17:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0004_attendancerecord'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='volunteers',
            field=models.ManyToManyField(related_name='events_attended', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.TimeField(default='00:00:00'),
        ),
    ]
