# Generated by Django 5.1.6 on 2025-05-10 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0007_attendancerecord_meeting_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancerecord',
            name='attended',
        ),
        migrations.RemoveField(
            model_name='attendancerecord',
            name='meeting_date',
        ),
        migrations.RemoveField(
            model_name='attendancerecord',
            name='meeting_time',
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='online_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='topic',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
