# Generated by Django 5.1.6 on 2025-05-10 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0008_remove_attendancerecord_attended_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='online_hours',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
