# Generated by Django 5.1.6 on 2025-05-29 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0009_alter_attendancerecord_online_hours'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
